### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by xncaffe** [ThanatosShinji/onnx-tool#1]
![50389F28-389F-43eb-8F8C-6D38ACDF1EC0](https://user-images.githubusercontent.com/30189373/183373896-358aa516-d889-4604-8bad-5650d3482d22.png)
Then report the following error！！！
![D1E85A50-8376-4357-89C9-8F00B3E391C8](https://user-images.githubusercontent.com/30189373/183374098-90985636-99c9-40fb-8edc-841fe0dad30c.png)
Implemented later, a separate “import onnx_tool” will cause this problem

**Comment by ThanatosShinji** [comment]
what do u mean a separate import?

**Comment by ThanatosShinji** [comment]
I've tested with this  [resnet18](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet18-v1-7.onnx) model. It seems ok.

**Comment by xncaffe** [comment]
> 

I mean “import onnx_tool” will error！

**Comment by xncaffe** [comment]
> I've tested with this [resnet18](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet18-v1-7.onnx) model. It seems ok.

Can you tell me your python version or other environment boards?

**Comment by ThanatosShinji** [comment]
> 
python 3.10(I believe python3 is enough).  onnx 1.12.  numpy 1.22.4

**Comment by ThanatosShinji** [comment]
> > 
> 
> I mean “import onnx_tool” will error！
can you share your code to reproduce the error? I believe this error is caused by variable name and script name conflict.

**Comment by xncaffe** [comment]
> > > 
> > 
> > 
> > I mean “import onnx_tool” will error！
> > can you share your code to reproduce the error? I believe this error is caused by variable name and script name conflict.

![1660221525(1)](https://user-images.githubusercontent.com/30189373/184135090-bb33ee95-e984-487a-80a2-27363340b3a0.png)

**Comment by ThanatosShinji** [comment]
I'm fixing it.

**Comment by ThanatosShinji** [comment]
0.2.1 has fixed this bug. please install and check pip install onnx-tool -i https://pypi.python.org/simple

**Comment by xncaffe** [comment]
> 0.2.1 has fixed this bug. please install and check pip install onnx-tool -i https://pypi.python.org/simple

big guy, awesome！！
![3CDA1336-4CC0-46d4-AEF9-133DF23DC3C8](https://user-images.githubusercontent.com/30189373/184268922-83433d85-e8ee-4d02-b94b-2eeb43743059.png)

**Comment by CescMessi** [comment]
I met the same problem in python=3.8.16 and onnx-tool=0.8.0, like that:

```shell
# python -m onnx_tool -h
Traceback (most recent call last):
  File "/opt/conda/envs/onnxtool/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/envs/onnxtool/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/conda/envs/onnxtool/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/envs/onnxtool/lib/python3.8/site-packages/onnx_tool/__init__.py", line 7, in <module>
    from .graph import Graph
  File "/opt/conda/envs/onnxtool/lib/python3.8/site-packages/onnx_tool/graph.py", line 8, in <module>
    from .node import create_node
  File "/opt/conda/envs/onnxtool/lib/python3.8/site-packages/onnx_tool/node.py", line 125, in <module>
    class Node():
  File "/opt/conda/envs/onnxtool/lib/python3.8/site-packages/onnx_tool/node.py", line 157, in Node
    def value_infer(self, intensors: list[Tensor], outtensors: list[Tensor]):
TypeError: 'type' object is not subscriptable
```

The `list[Tensor]` can not be used in python<3.9, could you consider using `typing.List` instead? @ThanatosShinji

**Comment by ThanatosShinji** [comment]
Yes, I should use List instead. Thank you for reporting!

Best Regards
________________________________

**Comment by ThanatosShinji** [comment]
@CescMessi the new release has fixed this.
