### ISSUE TITLE
auto_pad for average pooling layer

### ISSUE THREAD

**Issue by kinik93** [ThanatosShinji/onnx-tool#10]
Runtime error while concatenating tensor along a specific axis due to a not correct inferred shape after average pooling layer.

The issue can reproduced in this way
1.  Convert InceptionV3 Keras classifier (use the model available [here](https://keras.io/api/applications/inceptionv3/)) into onnx format
2. Run onnx-tool profiler on the converted model
3. Get this kind of error 
`ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 35 and the array at index 3 has size 33`

I'm currently using onnx-tool version 0.3.2

**Expected behavior**
The shape should be instead 35 as indicated also in the graph you can view with some plot utility tool like [Netron](https://netron.app/). I attach also a screenshot of the graph with the correct shape that can be taken from Netron app. 
![inception_v3_avgpool](https://user-images.githubusercontent.com/33391536/203124363-072921c7-0204-4472-988b-acbdfa21e6eb.PNG)

This issue could be solved reading the auto_pad property also for PoolBase node and computing the output shape in `pooling_shape_calc` method in different ways depending on `SAME_UPPER or SAME_LOWER` or `VALID` case

**Comment by ThanatosShinji** [comment]
Thx for your report! I've confirmed that it's a bug of auto_pad

**Comment by ThanatosShinji** [comment]
This issue has been fixed in v0.4.0.

**Comment by ThanatosShinji** [comment]
Closed as fixed
