### ISSUE TITLE
Bug in ReduceMean/ReduceMax/ReduceMin/ReduceSum operator shape inference

### ISSUE THREAD

**Issue by haojin2** [ThanatosShinji/onnx-tool#11]
**Describe the bug**
The parsing of `axes` in those operators is problematic when `axes` is not in the attributes. It will cause problems in shape inference if the output from the Reduce operation is used by a following op which has assumptions on the shape.

**To Reproduce**
Use the following script to generate a dummy model
```python
from torch.nn import Module
import torch

class Dummy(Module):
    def __init__(self):
        super(Dummy, self).__init__()

    def forward(self, x):
        return torch.unsqueeze(torch.sum(x, dim=1), 1)

model = Dummy()

x = torch.zeros((32, 10))

torch.onnx.export(model, x, "model.onnx")
```
then run:
`python3 -m onnx_tool -m profile -i model.onnx --names input -d input:f32:32x10`

**Proposed Fix**
Something similar to: https://github.com/ThanatosShinji/onnx-tool/blob/main/onnx_tool/node_profilers.py#L1090-L1093

**Comment by ThanatosShinji** [comment]
Thanks for your report!

**Comment by ThanatosShinji** [comment]
The issue you reported has been fixed in v0.5.1. Please be aware that node_profilers.py will be deprecated in the future. So this file is not included in this fix.

**Comment by haojin2** [comment]
Any ETA for 0.5.1 release?

**Comment by ThanatosShinji** [comment]
It's already released.
