### ISSUE TITLE
Missing type in `numpy_dtype2bytes` function

### ISSUE THREAD

**Issue by haojin2** [ThanatosShinji/onnx-tool#12]
**Describe the bug**
https://github.com/ThanatosShinji/onnx-tool/blob/main/onnx_tool/tensor.py#L220-L231
```
def numpy_dtype2bytes(ndtype):
    if ndtype == numpy.float32 or ndtype == numpy.int32:
        return 4
    if ndtype == numpy.float16:
        return 2
    if ndtype == numpy.int64 or ndtype == numpy.float64:
        return 8
    if ndtype == numpy.int8 or ndtype == numpy.uint8:
        return 1
    if ndtype.type == numpy.bytes_:
        return 256
    assert 0
```

This function will fail on `numpy.bool_` input.

**Proposed fix**
Just use something like
`return numpy.dtype(ndtype).itemsize`
instead of hardcoding the branchs.
Check:
https://stackoverflow.com/questions/16972501/size-of-data-type-using-numpy

**Comment by ThanatosShinji** [comment]
Thanks! After all model tests, this quick fix will be released to the main branch.

**Comment by ThanatosShinji** [comment]
v0.5.2 has been released to fix this bug. Please upgrade and check.
