### ISSUE TITLE
The meaning of metric 'memory' in the profile result

### ISSUE THREAD

**Issue by miniTsl** [ThanatosShinji/onnx-tool#16]
Is anybody so kind to help explain what the metric 'memory' stands for exactly in the profile result? I figure it covers the memory usage caused by model parameters and inference intermediate data… Thanks so much!!!

**Comment by ThanatosShinji** [comment]
> I figure it covers the memory usage caused by model parameters and inference intermediate data

Actually, this is what it means. The bytes count of parameters and output tensors(default as float).
For some 4k resolution CV models, this may be useful to decrease memory usage.
BTW, most inference frameworks will reuse intermediate data. So the memory count will be larger than the real inference case.

**Comment by miniTsl** [comment]
Thank you so much!
