### ISSUE TITLE
scatterND error when using model_profile on an .onnx file

### ISSUE THREAD

**Issue by YingHH1** [ThanatosShinji/onnx-tool#19]
I encountered an error when I use the following code to produce a MACS summary and shape onnx:

import onnx_tool
onnx_tool.model_profile('clipEncoder.onnx',saveshapesmodel='clipEncoder_shapes.onnx')

The following error occurs:
in onnx_tool/node.py:
def scatter_nd_impl(data, indices, updates, reduction='none'):  # type: ignore
    # Check tensor shapes
    assert indices.shape[-1] <= len(data.shape)
AssertionError

This is because since the expression is: 22<=2, due to:
indices.shape
(1, 1, 22)
indices[0,0,:]
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.], dtype=float32)
data.shape
(1, 77)
data[0,:]
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

The .onnx file was produced for the ClipEncoder in stable diffusion v2:
https://github.com/Stability-AI/stablediffusion/blob/main/ldm/modules/encoders/modules.py

under the class:
class FrozenOpenCLIPEmbedder(AbstractEncoder):
    ...
    def encode(self, text):
        with torch.no_grad():
            torch.onnx.export(self,text,"clipEncoder.onnx",opset_version=12)
        return self(text)

**Comment by ThanatosShinji** [comment]
> def encode(self, text):
with torch.no_grad():
torch.onnx.export(self,text,"clipEncoder.onnx",opset_version=12)
return self(text)

Please provide a test input of 'text'.

**Comment by YingHH1** [comment]
With classifier-free guidance, the text is an empty condition [''], or any conditional text, e.g. 

text
['cartoon style']

**Comment by YingHH1** [comment]
A simple way to recreate is just try:

python scripts/txt2img.py --prompt "a professional photograph of an astronaut riding a horse" --ckpt <path/to/768model.ckpt/> --config configs/stable-diffusion/v2-inference-v.yaml --H 768 --W 768  

or

python scripts/img2img.py --prompt "A fantasy landscape, trending on artstation" --init-img <path-to-img.jpg> --strength 0.8 --ckpt <path/to/model.ckpt>

**Comment by ThanatosShinji** [comment]
I've reproduced your issue. But, I've confirmed the inputs of scatterND are correctly calculated. And I've checked that there is no update code for  scatter_nd_impl.  

So I need more time to check whether this model is correctly exported or this is an invalid case of  scatter_nd_impl.

**Comment by ThanatosShinji** [comment]
There is a workaround solution:
```
def forward(self, tokens):  
      z = self.encode_with_transformer(tokens.to(self.device))
      return z
```
Do not export tokenize module as BERT does.

**Comment by ThanatosShinji** [comment]
For encode:
```
    def encode(self, text):
        token=open_clip.tokenize(text)
        with torch.no_grad():
            torch.onnx.export(self, token, "clipEncoder.onnx", opset_version=12)
        return self(token)
```

**Comment by YingHH1** [comment]
Thank you for the work around. Unfortunately, I still encounter an error:
  File "/home/usr1/anaconda3/envs/stableDiffusion/lib/python3.8/site-packages/onnx_tool/node.py", line 1672, in shape_infer
    assert raw == volume(newshape)
AssertionError

raw
78771
newshape
[77, 16, 64]
volume(newshape)
78848

Additionally, if I remove that line, I am able to produce the shape onnx file and the summary. However, the number of parameters seems off, since the onnx_tool summary gives the total:
Total            22,811,725,305  100%        1,338,963,850  100%        340,393,938  100%        _          _

But if one prints the total number of parameters:
ss=0
for p in self.model.parameters():
    ss=ss+len(p.flatten())
print(ss)
354032641

there seems to be a discrepancy: 340,393,938 vs 354,032,641.

I notice the warning:
Please note that Weight Tensors Sharing is detected:
Tensor:onnx::Reshape_3239
Shared by:
            Identity_4
            Identity_5
            Identity_6
            Identity_11
 ...
Tensor:onnx::Mul_3248
Shared by:
            Identity_3
            Identity_10
            Identity_17
            Identity_24
            Identity_31
            Identity_38
 ...
etc.

but I am unsure if this is the root cause.

**Comment by ThanatosShinji** [comment]
> assert raw == volume(newshape)

This should be a bug of v0.6.0. v0.6.1 was released yesterday to fix this. These summary print of v0.6.1:

Total | 23803402305 | 100% | 1944165092 | 100% | 352990169 | 100%
-- | -- | -- | -- | -- | -- | --

> Please note that Weight Tensors Sharing is detected:

ONNX will compress parameters into one tensor if some constant tensors are shared among layers. 
In the torch model, they will be two tensors.

**Comment by YingHH1** [comment]
Strange, I have upgraded the package via pip install -U onnx-tool, and the version is now v0.6.1, with the assert raw error fixed, but the summary still gives the incorrect information:

Total            22,811,725,305  100%        1,338,956,766  100%        340,393,938  100%        _          _

Could you let me know if I should change any other bits of the code to reproduce your summary result?

**Comment by YingHH1** [comment]
I used the command:
onnx_tool.model_profile('clipEncoder_noTokenizer.onnx',saveshapesmodel='clipEncoder_noTokenizer_shapes_new.onnx')

Could you let me know yours?
