### ISSUE TITLE
Matrix multiplication MACs error！

### ISSUE THREAD

**Issue by dongyangliu1996** [ThanatosShinji/onnx-tool#2]
![微信图片_20220901163306](https://user-images.githubusercontent.com/49853847/187869965-86ba476a-fbfd-4f90-ba6b-b6c5a24b82e8.jpg)
![微信图片_20220901163313](https://user-images.githubusercontent.com/49853847/187869976-39fa3228-832e-48ed-89e1-eccad64cb68e.jpg)

**Comment by tpoisonooo** [comment]
* `MatMul_219` got a wrong result. It should be 157351936
* Input shape looks weird, [12544,784] @  transpose([12544, 16])  ?   hope add inference shape checker

**Comment by ThanatosShinji** [comment]
Thanks for your report. The MACs number is wrong, for considering B Matrix as 2-dimension only. It will be fixed soon. 
But the input shapes should be just right.

**Comment by dongyangliu1996** [comment]
> Thanks for your report. The MACs number is wrong, for considering B Matrix as 2-dimension only. It will be fixed soon. But the input shapes should be just right.

Thank you！

**Comment by ThanatosShinji** [comment]
v0.2.7 has fixed this issue. please check. pip install onnx-tool==0.2.7.

**Comment by ThanatosShinji** [comment]
For A: 1x12x256x64, B: 1x12x64x256   v0.2.6: MACs=2,359,296   v0.2.7=50,331,648

**Comment by dongyangliu1996** [comment]
> v0.2.7 has fixed this issue. please check. pip install onnx-tool==0.2.7.

I have install onnx-tools 0.2.7，the MACs number is correct. Thank you very much!
