### ISSUE TITLE
3D convolution operator support

### ISSUE THREAD

**Issue by karthickai** [ThanatosShinji/onnx-tool#20]
Thanks for the amazing library. But the tool not supporting the 3D convolution operator. Getting errors in shape infer

**Comment by karthickai** [comment]
I solved this issue, I added new 3D convolution operator support in node.py, and I request PR.

**Comment by ThanatosShinji** [comment]
Thanks for your contribution!

**Comment by ThanatosShinji** [comment]
Already merged. THX!
