### ISSUE TITLE
Hei, I got A problem here, which said "unsupported operand type(s) for //: 'str' and 'int' " when I called the function onnx_tool.model_profile to load my onnx model

### ISSUE THREAD

**Issue by LiangZai-Embedded** [ThanatosShinji/onnx-tool#22]
Traceback (most recent call last):
  File "inference.py", line 11, in <module>
    onnx_tool.model_profile(model_path) # pass file name
  File "/home/pi/.local/lib/python3.7/site-packages/onnx_tool/__init__.py", line 90, in model_profile
    g.shape_infer(dynamic_shapes)
  File "/home/pi/.local/lib/python3.7/site-packages/onnx_tool/graph.py", line 645, in shape_infer
    oshapes = node.shape_infer(itensors)
  File "/home/pi/.local/lib/python3.7/site-packages/onnx_tool/node.py", line 1665, in shape_infer
    remain = raw // -sum
TypeError: unsupported operand type(s) for //: 'str' and 'int'

**Comment by ThanatosShinji** [comment]
Hi, your information is so little. But I guess that your model has dynamic input shapes(e.g. input:1x3xhxw). The dynamic input model needs to feed a specific shape to model_profile.

**Comment by LiangZai-Embedded** [comment]
> Hi, your information is so little. But I guess that your model has dynamic input shapes(e.g. input:1x3xhxw). The dynamic input model needs to feed a specific shape to model_profile.

My model is converted from keras to onnx , in keras the input shape is (None，90，3，1), I printed the value of  newshape in node.py which is [-1,1,90,3]，sum is -270, src shape is[unk__17,90,3,1], raw is unk__17unk__17..(repeat) However if delete these lines from 1664 to 1670 I also get the output of the model profile.Is it the correct output?I only care about the parameters^_^

**Comment by ThanatosShinji** [comment]
You may refer https://github.com/ThanatosShinji/onnx-tool/blob/main/benchmark/samples.py#L42 this sample to set the input shape with model_profile call.

**Comment by LiangZai-Embedded** [comment]
> You may refer https://github.com/ThanatosShinji/onnx-tool/blob/main/benchmark/samples.py#L42 this sample to set the input shape with model_profile call.

Thanks, I'll try it later.

**Comment by ThanatosShinji** [comment]
If there is no more feedback information, the issue will be closed as a question.
