### ISSUE TITLE
error occur when i use onnx_tool to freeze input tensor shape of gpt2-10.onnx model, then infer the shape, finally store the shaped onnx model. 

### ISSUE THREAD

**Issue by smilexin** [ThanatosShinji/onnx-tool#27]
**Describe the bug**
When I run 'model_shape_infer' for gpt2-10.onnx,  "index 1 is out of bounds for axis 0 with size 1" error occur.

**To Reproduce**
* Prepare gpt2-10.onnx model and put at the ./Public dir 
* Run the below code

import onnx_tool
onnx_tool.model_shape_infer(m='./Public/gpt2-10.onnx', dynamic_shapes={'input1':(1,1,8)}, saveshapesmodel='./Public/gpt2-10_shaped.onnx')

**Expected behavior**
Get the final shaped onnx model with the static input tensor shape [1,1,8],
The output shaped onnx can use onnxruntime for inference.

**Screenshots**
Error like this:

![WXWorkCapture_16853339081349](https://github.com/ThanatosShinji/onnx-tool/assets/7620543/cc3dceb1-0d2f-4a8e-8c3e-ac02dff76e50)

**Comment by ThanatosShinji** [comment]
Hi, you passed a shape list to onnx_tool. But currently, it requires a numpy array with that shape:
e.g. dynamic_shapes=
            {
                'input1': create_ndarray_int64((1, 1, 8)),
            }.

If can find more model's input configurations in the data/config.py file.

Why not just shape list? Because sometime the value of the tensor needs to be used to calculate the shape sizes.

**Comment by smilexin** [comment]
> Hi, you passed a shape list to onnx_tool. But currently, it requires a numpy array with that shape: e.g. dynamic_shapes= { 'input1': create_ndarray_int64((1, 1, 8)), }.
> 
> You can find more model's input configurations in the data/config.py file.
> 
> Why not just shape list? Because sometime the value of the tensor needs to be used to calculate the shape sizes.

Thanks, it works use "create_ndarray_int64" to construct shape, and I get the genarated shaped model.

However when I use onnxruntime to infer the shaped model, error occur:
 onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from ./Public/gpt2-10_shaped_1x1x8.onnx failed:This is an invalid model. In Node, ("Unsqueeze_23", Unsqueeze, "", -1) : ("169": tensor(int64),) -> ("192": tensor(int64),) , Error Node (Unsqueeze_23) has input size 1 not in range [min=2, max=2].

Can use the following code to reproduce the question:

import onnxruntime as ort
import numpy as np
sess = ort.InferenceSession("./Public/gpt2-10_shaped_1x1x8.onnx")
x = np.full((1,1,8), 1)
x = x.astype(np.int64)
ret = sess.run(["output1", "output13"], {"input1": x})
print(np.shape(ret[0][0]))
print(np.array2string(ret[0][0], separator=', '))
print(np.shape(ret[1][0]))
print(np.array2string(ret[1][0], separator=', '))

Thanks, : )

**Comment by ThanatosShinji** [comment]
It's not supported and recommended to use onnx_tool's shape model for OnnxRuntime to infer with. Because ORT has a strict check for each dynamic tensor's data type. On the other hand, it's not necessary to provide shape info to ORT.

Here is the suggested usage with ORT:
a. Add dump tensor name to ORT refers to [code](benchmark/ort_infer.py)
b. constant folding before inference.

**Comment by smilexin** [comment]
> It's not supported and recommended to use onnx_tool's shape model for OnnxRuntime to infer with. Because ORT has a strict check for each dynamic tensor's data type. On the other hand, it's not necessary to provide shape info to ORT.
> 
> Here is the suggested usage with ORT: a. Add dump tensor name to ORT refers to [code](../blob/main/benchmark/ort_infer.py) b. constant folding before inference.

soga, got it , thanks very much, goodluck~
