### ISSUE TITLE
memory compression question

### ISSUE THREAD

**Issue by wangxdgg** [ThanatosShinji/onnx-tool#28]
I have some questions when looking at the memory compression section, is the middle layer memory compressed here, or weight memory? How did you achieve such a high compression ratio.

**Comment by ThanatosShinji** [comment]
It's the activation compression, no weight memory here.
When one activation tensor is consumed by all its consumers, its memory can be freed to the next layer's activation tensor.

**Comment by wangxdgg** [comment]
So can it be interpreted as peak activation memory usage？

**Comment by ThanatosShinji** [comment]
You can say it's the peak activation memory usage with dynamic activation allocation.

**Comment by wangxdgg** [comment]
OK，I got you, thanks a lot !
