### ISSUE TITLE
ValueError: Input data_batch_0's shape is dynamic, please set it a fixed input dimension

### ISSUE THREAD

**Issue by aureosun** [ThanatosShinji/onnx-tool#3]
I use the lib as demo,and got the following result, please help me to see the problem

python.exe D:/onnx_tool_test.py
Traceback (most recent call last):
  File "D:\onnx_tool_test.py", line 8, in <module>
    onnx_tool.model_profile(modelpath, {'input': create_ndarray_f32((1, 16, 3, 224, 224))}, None)
  File "C:\xxx\.conda\envs\pytorchLearn\lib\site-packages\onnx_tool\__init__.py", line 258, in model_profile
    graph_profile(m.graph, dynamic_shapes, verbose, hidden_ops=hidden_ops)
  File "C:\xxx\.conda\envs\pytorchLearn\lib\site-packages\onnx_tool\__init__.py", line 147, in graph_profile
    tmap, pmap = infer_shapes(graph, dynamic_shapes, verbose=verbose)
  File "C:\xxx\.conda\envs\pytorchLearn\lib\site-packages\onnx_tool\__init__.py, line 86, in infer_shapes
    raise ValueError(f"Input {input.name}'s shape is dynamic, please set it a fixed input dimension")
ValueError: Input data_batch_0's shape is dynamic, please set it a fixed input dimension

**Comment by ThanatosShinji** [comment]
as the log said :ValueError: Input data_batch_0's shape is dynamic.  You should set a fixed input shape for the data_batch_0 tensor.

**Comment by ThanatosShinji** [comment]
you can refer data/Profile.md for dynamic input shapes' usage or data/Tensors.md for Modify input and output tensors

**Comment by aureosun** [comment]
as below, I just set the input shape and then got the result above
onnx_tool.model_profile(modelpath, {'input': create_ndarray_f32((1, 16, 3, 224, 224))}, None)

**Comment by ThanatosShinji** [comment]
What I saw is not your 'input' tensor, it's the 'data_batch_0' tensor's shape.

**Comment by ThanatosShinji** [comment]
This issue will be closed if no more information is provided.
