### ISSUE TITLE
How to keep conv-W conv-B shape, when save_model with shapeonly True

### ISSUE THREAD

**Issue by janicevidal** [ThanatosShinji/onnx-tool#34]
![image](https://github.com/ThanatosShinji/onnx-tool/assets/29887681/65b9c549-103a-47f9-860c-d9596b00d875)
onnx_tool.model_shape_infer(modelpath, None, "r50_shape_only.onnx", shapesonly=True)

**Comment by ThanatosShinji** [comment]
A good suggestion! I will consider adding weight to the next release.

**Comment by ThanatosShinji** [comment]
The commit of the main branch has supported weight shapes. You can checkout the main branch code for this feature. pypi release will be determined with other issues.

**Comment by janicevidal** [comment]
> The commit of the main branch has supported weight shapes. You can checkout the main branch code for this feature. pypi release will be determined with other issues.

Get it, thanks.
