### ISSUE TITLE
MobileNetV2 MACs don't match

### ISSUE THREAD

**Issue by thestarivore** [ThanatosShinji/onnx-tool#4]
I tried to use the profiling in orther to get the MACs of a MobileNetV2 model, but I get 0 MACs for many layers including Conv2D, am I doing something wrong or is a bug?

**To Reproduce**
I run the following command:
`python3 -m onnx_tool -i mobilenet_v2.onnx --mode profile --dynamic_inputs mobilenetv2_1.00_160_input:f32:1x3x160x160 
`

**Screenshots**
Here is what I get:
![image](https://user-images.githubusercontent.com/22894195/188746882-50e0b30d-a344-4d48-b5ac-6c93852457c4.png)

**Additional context**
You can download my ONNX model from here: [https://ufile.io/wke6jg58](mobilenetv2.onnx)

Thank you in advance.

**Comment by ThanatosShinji** [comment]
Hi, it seems your model is a TensorFlow-converted model. So your input should be 1x160x160x3, because there is a dummy transpose layer for the tensor format conversion at the beginning of the model.

**Comment by ThanatosShinji** [comment]
This issue will be closed if no more information is provided.
