### ISSUE TITLE
when I profiles yolop.onnx It has problem

### ISSUE THREAD

**Issue by Arche-Logos** [ThanatosShinji/onnx-tool#5]
modelpath = "yolop-1280-1280.onnx"

inputs = {'image:0': create_ndarray_f32((1,3,1280,1280))}

onnx_tool.model_profile(modelpath, inputs, None) 

Traceback (most recent call last):
    File "onnxAnalyze.py", line 11, in <module>
    onnx_tool.model_profile(modelpath, inputs, None)  # save profile table to csv file
  File "onnx_tool\__init__.py", line 258, in model_profile
    graph_profile(m.graph, dynamic_shapes, verbose, hidden_ops=hidden_ops)
  File "onnx_tool\__init__.py", line 147, in graph_profile
    tmap, pmap = infer_shapes(graph, dynamic_shapes, verbose=verbose)
  File "nnx_tool\__init__.py", line 115, in infer_shapes
    outtensors = node_infer_shape(node, ins)
  File "onnx_tool\node_profilers.py", line 1498, in node_infer_shape
    return profler.infer_shape(ins)
  File "onnx_tool\node_profilers.py", line 222, in infer_shape
    return [intensors[0] + intensors[1]]
ValueError: operands could not be broadcast together with shapes (1,3,160,160,6) (1,1,160,160,2)

**Comment by ThanatosShinji** [comment]
seems something is wrong with this model's shape inference. Can you share this model with me?

**Comment by Arche-Logos** [comment]
> seems something is wrong with this model's shape inference. Can you share this model with me?
[Baidu Drive](https://pan.baidu.com/s/1elUGcx7CZkkjEoYhTMwTRQ) code: 8gin  model is yolop.onnx.
and I find when I set the siput such as "inputs = {'images:0': create_ndarray_f32((1, 3, 125, 414))}" it not used.

**Comment by ThanatosShinji** [comment]
> and I find when I set the siput such as "inputs = {'images:0': create_ndarray_f32((1, 3, 125, 414))}" it not used.

you set the input tensor name as 'images:0', but I think it's 'images' from 'yolop-1280-1280.onnx'

**Comment by ThanatosShinji** [comment]
> ValueError: operands could not be broadcast together with shapes (1,3,160,160,6) (1,1,160,160,2)

the bug has fixed in v0.2.11.

> inputs = {'images:0': create_ndarray_f32((1, 3, 125, 414))}

this input shape is not valid for yolop, it requires H&W are padded to 32, you should try (1,3,128,416)
