### ISSUE TITLE
Have problem when profiling Twins, Swin and SwiftFormer

### ISSUE THREAD

**Issue by MurazeKrinas** [ThanatosShinji/onnx-tool#56]
Dear author,

I'm having trouble when profiling Twin Transformer ([arxiv.org/abs/2104.13840](https://arxiv.org/abs/2104.13840)), Swin Transformer (https://arxiv.org/abs/2103.14030), and SwiftFormer (https://arxiv.org/abs/2303.15446) while using similar methods with the previous issue (https://github.com/ThanatosShinji/onnx-tool/issues/55). The bug occurred with the original ONNX file which did not perform constant-folding, I think that there is a problem with the MOD operator or something else. The error has been described in the image and the ONNX file is attached below.

Hope to hear from you soon.

With SwiftFormer:
![image](https://github.com/ThanatosShinji/onnx-tool/assets/88036898/53401886-0d41-43d4-a2cb-1bbcb582e2f5)

With Twins and Swin:
![image](https://github.com/ThanatosShinji/onnx-tool/assets/88036898/931529ba-c96c-48ab-8002-0f3425ed272e)

ONNX File: https://drive.google.com/drive/folders/1HahqFonb9zlGw2X6vQcqrL-K0FqaIXja?usp=share_link

**Comment by ThanatosShinji** [comment]
The twins and swin's issue has been fixed. But I can't reproduce the issue from SwiftFormer.

**Comment by MurazeKrinas** [comment]
So...what should I do now? Do you need its source code? Will you fix it in the future or...I should change another model 😆

**Comment by ThanatosShinji** [comment]
You can profile these 3 models with the main branch code

Best Regards
________________________________

**Comment by MurazeKrinas** [comment]
It still raises error! I don't see any commit in term of fixing the bug with SwiftFormer. Do you miss something?

**Comment by ThanatosShinji** [comment]
With this head commit, I have no problem with SwiftFormer-S.onnx

**Comment by ThanatosShinji** [comment]
I see. the bug occurs without constant_folding

**Comment by ThanatosShinji** [comment]
The bug fix is done.

**Comment by MurazeKrinas** [comment]
I just turned on my computer to do work and your comment appeared as a salvation! Everything worked well, you are really talented and hardworking, I really appreciate it! Thank you for your efforts in the past 3 days, wish you success in your next projects <3
