### ISSUE TITLE
BUG about shape_infer()

### ISSUE THREAD

**Issue by Like2021** [ThanatosShinji/onnx-tool#58]
I think nodes like or can be used without shape_infer?

```shell
File "/home/xxxx/anaconda3/envs/onnx/lib/python3.8/site-packages/onnx_tool/node.py", line 158, in value_infer
  raise NotImplementedError(f'this Node {self.op_type}-{self.name} has no value_infer')
NotImplementedError: this Node Or-/Or has no value_infer

**Comment by ThanatosShinji** [comment]
Do you mean without value_infer?

**Comment by ThanatosShinji** [comment]
I think the real problem here is your model with Or operator is not supported.

**Comment by Like2021** [comment]
Thanks for your answer.

I guess that or operator is not supported. Could you teach me how to manually support or skip the or operator?

I tried to skip this operator in the code, 
https://github.com/ThanatosShinji/onnx-tool/blob/f06228c4edce44bc33025db9b1bbcbd018173d9f/onnx_tool/graph.py#L823C37
but this will affect the shape infer of subsequent operators. I am confused about this and don't know how to solve it.

**Comment by ThanatosShinji** [comment]
I've added this operator to the main branch. you can check out this branch to use.

**Comment by Like2021** [comment]
Thanks for your quick reply!
