### ISSUE TITLE
support group query in attention module without replicate weight

### ISSUE THREAD

**Issue by cliffsong94** [ThanatosShinji/onnx-tool#68]
**Is your feature request related to a problem? Please describe.**

matmul 
inputs [1, 4, 8, 64, 64] query, [1, 4, 1, 64, 2048] key
outputs [1, 4, 1, 64, 2048]
which is wrong

**Describe the solution you'd like**
https://github.com/ThanatosShinji/onnx-tool/blob/125836d486a03cb3dbbef05f5412803ff86993db/onnx_tool/node.py#L688

change this line to 
 batchshape = xshape[:-2] if len(xshape) >= len(wshape) else wshape[:-2]

**Comment by cliffsong94** [comment]
yeah, it is even better.

**Comment by ThanatosShinji** [comment]
fixed in this commit 7d8cca70
