### ISSUE TITLE
onnx operation'split'  its parameter 'split' exists as 'input' not attr.

### ISSUE THREAD

**Issue by zhouguoqing99** [ThanatosShinji/onnx-tool#8]
onnx operation'split'  its parameter 'split' exists as 'input' not attr.

srccode:

def auto_add_attributes(atts, attnames, obj):
    for att in atts:
        if att.name in attnames:
            obj.__setattr__(att.name, get_attribute_data(att))

class Split(NodeBase):
    def __init__(self, nodeproto):
        super().__init__(nodeproto)
        attnames = ['axis', 'split']
        self.axis = None
        self.split = None
        auto_add_attributes(nodeproto.attribute, attnames, self)

so  split can not be got.

**Comment by ThanatosShinji** [comment]
Can you share your model with me? I need to add this to test cases.
